### ISSUE TITLE
Im Darkmode sind manche Admonitions nicht gut dargestellt

### ISSUE THREAD

**Issue by schnaitter** [quadriga-dk/Book_Template#29]
Die Admonitions Übung, Lernziel und Hinweis sind im Darkmode nicht gut zu lesen. Der Kontrast zwischen Hintergrund und Schriftfarbe ist nicht ausreichend. 

Keypoints und Achtung sind gut zu lesen. Lösung auch noch.

**Comment by lam1aa** [comment]
thank you for your feedback. I will work on it.
