### ISSUE TITLE
add internal links to the chapters listed in in the intro (for example: siehe Kapitel "Präambel")

### ISSUE THREAD

**Issue by esamoilo** [quadriga-dk/Book_Template#48]
@Lamia I tried to enter the internal links similar to Hannes examples, but it did not work for me. 
It should be smth like ({numref}`%s Markdown<formatierung:markdown>`

**Comment by schnaitter** [comment]
Did you create the reference on the page?

`(formatierung:admonitions)=` or similar needs to be added directly before a heading.

**Comment by lam1aa** [comment]
I have updated the links. #50
